import { Country } from "@/interfaces/Country.interface";

export const countriesTravelledTo: Country[] = [
  { name: "Albania", year: 2022, posts: ["post-1", "post-2", "post-3"] },
  { name: "Australia", year: 2013, posts: [] },
  { name: "Bosnia and Herzegovina", year: 2022, posts: [] },
  { name: "Brunei", year: 2016, posts: [] },
  { name: "Cambodia", year: 2019, posts: [] },
  { name: "China", year: 2019, posts: [] },
  { name: "Croatia", year: 2022, posts: [] },
  { name: "Czech Republic", year: 2022, posts: [] },
  { name: "Germany", year: 2022, posts: [] },
  { name: "Hungary", year: 2022, posts: [] },
  { name: "Indonesia", year: 2023, posts: [] },
  { name: "Italy", year: 2013, posts: [] },
  { name: "Japan", year: 2019, posts: [] },
  { name: "Jordan", year: 2022, posts: [] },
  { name: "Laos", year: 2019, posts: [] },
  { name: "Malaysia", year: 2022, posts: [] },
  { name: "Malta", year: 2022, posts: [] },
  { name: "Mexico", year: 2022, posts: [] },
  { name: "Montenegro", year: 2022, posts: [] },
  { name: "Myanmmar", year: 2019, posts: [] },
  { name: "New Zealand", year: 2017, posts: [] },
  { name: "Singapore", year: 2023, posts: [] },
  { name: "South Korea", year: 2019, posts: [] },
  {
    name: "Switzerland",
    year: 2022,
    posts: ["post-1", "post-2", "post-3", "post-4", "post-5"],
  },
  { name: "Taiwan", year: 2018, posts: [] },
  { name: "Thailand", year: 2022, posts: [] },
  { name: "USA", year: 2022, posts: [] },
  { name: "Vietnam", year: 2020, posts: [] },
];
