import { Continent, Country } from "@/interfaces/Country.interface";

export const countriesData: Country[] = [
  {
    name: "Afghanistan",
    dialCode: "+93",
    code: "AF",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Aland-Islands",
    dialCode: "+358",
    code: "AX",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Albania",
    dialCode: "+355",
    code: "AL",
    visited: true,
    year: 2022,
    posts: [
      "3-Reasons-To-Travel-To-Albania",
      "Roaming-Through-Europe:-My-Solo-Backpacking-Adventure",
    ],
    continent: Continent.EUROPE,
    introduction:
      "Albania is a small country in Southeastern Europe with a rich history and stunning natural beauty. Its coastline, mountain ranges, and lakes make it a popular destination for outdoor enthusiasts, while its cities offer historic landmarks, bustling markets, and a vibrant nightlife. Albanian cuisine is a unique blend of Mediterranean and Balkan influences. Albania is a diverse and dynamic country that combines ancient traditions with modern innovations, making it a destination worth exploring.",
  },
  {
    name: "Algeria",
    dialCode: "+213",
    code: "DZ",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Samoa",
    dialCode: "+1684",
    code: "AS",
    visited: false,
    posts: [],
    continent: Continent.OCEANIA,
  },
  {
    name: "Andorra",
    dialCode: "+376",
    code: "AD",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Angola",
    dialCode: "+244",
    code: "AO",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Anguilla",
    dialCode: "+1264",
    code: "AI",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Antarctica",
    dialCode: "+672",
    code: "AQ",
    visited: false,
    posts: [],
    continent: Continent.ANTARCTICA,
  },
  {
    name: "Antigua and Barbuda",
    dialCode: "+1268",
    code: "AG",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Argentina",
    dialCode: "+54",
    code: "AR",
    visited: false,
    posts: [],
    continent: Continent.SOUTH_AMERICA,
  },
  {
    name: "Armenia",
    dialCode: "+374",
    code: "AM",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Aruba",
    dialCode: "+297",
    code: "AW",
    visited: false,
    posts: [],
    continent: Continent.SOUTH_AMERICA,
  },
  {
    name: "Australia",
    dialCode: "+61",
    code: "AU",
    year: 2011,
    visited: true,
    posts: [],
    continent: Continent.OCEANIA,
    introduction:
      "Australia is a country and continent located in the southern hemisphere, surrounded by the Indian and Pacific Oceans. With a population of over 25 million people, it is the world's sixth-largest country by total area. Australia is known for its stunning landscapes, including the vast Outback, tropical rainforests, and beautiful beaches. The country is home to a rich and diverse wildlife, with many unique species found only in Australia. Its major cities, including Sydney, Melbourne, and Brisbane, are vibrant and cosmopolitan, with a strong arts and culture scene, as well as a reputation for great food and wine.",
  },
  {
    name: "Austria",
    dialCode: "+43",
    code: "AT",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Azerbaijan",
    dialCode: "+994",
    code: "AZ",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Bahamas",
    dialCode: "+1242",
    code: "BS",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Bahrain",
    dialCode: "+973",
    code: "BH",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Bangladesh",
    dialCode: "+880",
    code: "BD",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Barbados",
    dialCode: "+1246",
    code: "BB",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Belarus",
    dialCode: "+375",
    code: "BY",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Belgium",
    dialCode: "+32",
    code: "BE",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Belize",
    dialCode: "+501",
    code: "BZ",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Benin",
    dialCode: "+229",
    code: "BJ",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Bermuda",
    dialCode: "+1441",
    code: "BM",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Bhutan",
    dialCode: "+975",
    code: "BT",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Bolivia",
    dialCode: "+591",
    code: "BO",
    visited: false,
    posts: [],
    continent: Continent.SOUTH_AMERICA,
  },
  {
    name: "Bosnia-and-Herzegovina",
    dialCode: "+387",
    code: "BA",
    visited: true,
    year: 2022,
    posts: [],
    continent: Continent.EUROPE,
    introduction:
      "Bosnia is a small country located in the Balkan region of Europe, known for its stunning natural beauty, fascinating history, and warm hospitality. The country offers a unique blend of eastern and western cultures, with influences from the Ottoman Empire and Austro-Hungarian Empire still visible in its architecture and traditions. Bosnia is home to a variety of stunning landscapes, including the rugged peaks of the Dinaric Alps, rolling hills and valleys, and the sparkling waters of the Adriatic Sea. Visitors to Bosnia can explore historic cities like Sarajevo, Mostar, and Banja Luka, sample delicious local cuisine, and experience the warm and welcoming culture of this beautiful country.",
  },
  {
    name: "Botswana",
    dialCode: "+267",
    code: "BW",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Brazil",
    dialCode: "+55",
    code: "BR",
    visited: false,
    posts: [],
    continent: Continent.SOUTH_AMERICA,
  },
  {
    name: "Brunei",
    dialCode: "+673",
    code: "BN",
    visited: true,
    year: 2016,
    posts: [],
    continent: Continent.ASIA,
    introduction:
      "Brunei is a small country located on the northern coast of the island of Borneo, known for its rich history, beautiful architecture, and stunning natural beauty. The country is ruled by a sultan, and its culture is deeply influenced by Islam. Visitors to Brunei can explore the opulent palaces and mosques, stroll through charming villages and bustling markets, and enjoy the country's lush rainforests, pristine beaches, and crystal-clear waters. Brunei is also home to a variety of unique flora and fauna, including the endangered proboscis monkey. Whether you're interested in history, culture, or nature, Brunei has something to offer every traveler.",
  },
  {
    name: "Bulgaria",
    dialCode: "+359",
    code: "BG",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Burkina Faso",
    dialCode: "+226",
    code: "BF",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Burundi",
    dialCode: "+257",
    code: "BI",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Cambodia",
    dialCode: "+855",
    code: "KH",
    visited: true,
    year: 2019,
    posts: [],
    continent: Continent.ASIA,
    introduction:
      "Cambodia is a fascinating country located in Southeast Asia, known for its rich history, stunning architecture, and beautiful landscapes. The country is home to the iconic Angkor Wat temple complex, as well as many other ancient ruins and temples that provide a glimpse into Cambodia's rich cultural heritage. Visitors to Cambodia can also enjoy the country's beautiful beaches, lush jungles, and charming towns and cities. Cambodia's capital city, Phnom Penh, is a bustling metropolis with a vibrant arts and culture scene, while Siem Reap, the gateway to Angkor Wat, offers a more laid-back atmosphere. Whether you're interested in history, culture, or nature, Cambodia has something to offer every traveler.",
  },
  {
    name: "Cameroon",
    dialCode: "+237",
    code: "CM",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Canada",
    dialCode: "+1",
    code: "CA",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Cape Verde",
    dialCode: "+238",
    code: "CV",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Cayman Islands",
    dialCode: "+ 345",
    code: "KY",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Central African Republic",
    dialCode: "+236",
    code: "CF",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Chad",
    dialCode: "+235",
    code: "TD",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Chile",
    dialCode: "+56",
    code: "CL",
    visited: false,
    posts: [],
    continent: Continent.SOUTH_AMERICA,
  },
  {
    name: "China",
    dialCode: "+86",
    code: "CN",
    visited: true,
    year: 2019,
    posts: [],
    continent: Continent.ASIA,
    introduction:
      "China is a vast country located in East Asia, known for its rich history, diverse culture, and stunning landscapes. Visitors to China can explore ancient landmarks like the Great Wall, the Forbidden City, and the Terracotta Warriors, as well as modern marvels like the Shanghai Tower and the Bird's Nest Olympic Stadium. The country is also home to a variety of natural wonders, including the Yangtze River, the Himalayan Mountains, and the karst peaks of Guilin. Chinese cuisine is renowned around the world, with each region offering its own unique flavors and specialties. With so much to see and do, China is a destination that's sure to leave a lasting impression on any traveler.",
  },
  {
    name: "Colombia",
    dialCode: "+57",
    code: "CO",
    visited: false,
    posts: [],
    continent: Continent.SOUTH_AMERICA,
  },
  {
    name: "Comoros",
    dialCode: "+269",
    code: "KM",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Congo",
    dialCode: "+242",
    code: "CG",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Congo, The Democratic Republic of the Congo",
    dialCode: "+243",
    code: "CD",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Cook Islands",
    dialCode: "+682",
    code: "CK",
    visited: false,
    posts: [],
    continent: Continent.OCEANIA,
  },
  {
    name: "Costa Rica",
    dialCode: "+506",
    code: "CR",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Cote d'Ivoire",
    dialCode: "+225",
    code: "CI",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Croatia",
    dialCode: "+385",
    code: "HR",
    visited: true,
    year: 2022,
    posts: [],
    continent: Continent.EUROPE,
    introduction:
      "Croatia is a beautiful country located on the eastern coast of the Adriatic Sea, known for its stunning beaches, crystal-clear waters, and historic cities. Visitors to Croatia can explore the charming streets of Dubrovnik, a UNESCO World Heritage Site, as well as the lively capital city of Zagreb and the ancient Roman ruins of Split. The country is also home to a variety of natural wonders, including the Plitvice Lakes National Park, with its cascading waterfalls and turquoise lakes. Croatian cuisine is a delicious blend of Mediterranean and Central European influences, with fresh seafood, grilled meats, and hearty stews all on offer. With its rich history, beautiful landscapes, and warm hospitality, Croatia is a destination that's sure to delight any traveler.",
  },
  {
    name: "Cuba",
    dialCode: "+53",
    code: "CU",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Cyprus",
    dialCode: "+357",
    code: "CY",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Czech-Republic",
    dialCode: "+420",
    code: "CZ",
    visited: true,
    year: 2022,
    posts: [],
    continent: Continent.EUROPE,
    introduction:
      "The Czech Republic is a beautiful country located in the heart of Europe, known for its stunning architecture, rich history, and vibrant culture. Visitors to the Czech Republic can explore the historic streets of Prague, a city famous for its Gothic spires, Baroque churches, and charming cafes. The country is also home to a variety of ancient castles, including the stunning Karlštejn Castle, as well as natural wonders like the Bohemian Switzerland National Park, with its towering sandstone formations and stunning views. Czech cuisine is hearty and delicious, with traditional dishes like goulash, dumplings, and roasted meats all on offer. With its rich history, stunning landscapes, and warm hospitality, the Czech Republic is a destination that's sure to leave a lasting impression on any traveler.",
  },
  {
    name: "Denmark",
    dialCode: "+45",
    code: "DK",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Djibouti",
    dialCode: "+253",
    code: "DJ",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Dominican Republic",
    dialCode: "+1849",
    code: "DO",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Ecuador",
    dialCode: "+593",
    code: "EC",
    visited: false,
    posts: [],
    continent: Continent.SOUTH_AMERICA,
  },
  {
    name: "Egypt",
    dialCode: "+20",
    code: "EG",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "El Salvador",
    dialCode: "+503",
    code: "SV",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Equatorial Guinea",
    dialCode: "+240",
    code: "GQ",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Eritrea",
    dialCode: "+291",
    code: "ER",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Estonia",
    dialCode: "+372",
    code: "EE",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Ethiopia",
    dialCode: "+251",
    code: "ET",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Falkland Islands (Malvinas)",
    dialCode: "+500",
    code: "FK",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Faroe Islands",
    dialCode: "+298",
    code: "FO",
    visited: false,
    posts: [],
    continent: Continent.SOUTH_AMERICA,
  },
  {
    name: "Fiji",
    dialCode: "+679",
    code: "FJ",
    visited: false,
    posts: [],
    continent: Continent.OCEANIA,
  },
  {
    name: "Finland",
    dialCode: "+358",
    code: "FI",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "France",
    dialCode: "+33",
    code: "FR",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "French Guiana",
    dialCode: "+594",
    code: "GF",
    visited: false,
    posts: [],
    continent: Continent.SOUTH_AMERICA,
  },
  {
    name: "French Polynesia",
    dialCode: "+689",
    code: "PF",
    visited: false,
    posts: [],
    continent: Continent.OCEANIA,
  },
  {
    name: "Gabon",
    dialCode: "+241",
    code: "GA",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Gambia",
    dialCode: "+220",
    code: "GM",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Georgia",
    dialCode: "+995",
    code: "GE",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Germany",
    dialCode: "+49",
    code: "DE",
    visited: true,
    year: 2022,
    posts: [],
    continent: Continent.EUROPE,
    introduction:
      "Germany is a fascinating country located in the heart of Europe, known for its rich history, stunning architecture, and vibrant culture. Visitors to Germany can explore the historic streets of Berlin, a city famous for its landmarks like the Brandenburg Gate and Checkpoint Charlie, as well as its vibrant arts and nightlife scene. The country is also home to a variety of ancient castles, including the stunning Neuschwanstein Castle, as well as natural wonders like the Black Forest and the Bavarian Alps. German cuisine is hearty and delicious, with traditional dishes like sausages, pretzels, and beer all on offer. With its rich history, stunning landscapes, and warm hospitality, Germany is a destination that's sure to delight any traveler.",
  },
  {
    name: "Ghana",
    dialCode: "+233",
    code: "GH",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Gibraltar",
    dialCode: "+350",
    code: "GI",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Greece",
    dialCode: "+30",
    code: "GR",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Greenland",
    dialCode: "+299",
    code: "GL",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Grenada",
    dialCode: "+1473",
    code: "GD",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Guadeloupe",
    dialCode: "+590",
    code: "GP",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Guam",
    dialCode: "+1671",
    code: "GU",
    visited: false,
    posts: [],
    continent: Continent.OCEANIA,
  },
  {
    name: "Guatemala",
    dialCode: "+502",
    code: "GT",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Guinea",
    dialCode: "+224",
    code: "GN",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Guinea-Bissau",
    dialCode: "+245",
    code: "GW",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Guyana",
    dialCode: "+595",
    code: "GY",
    visited: false,
    posts: [],
    continent: Continent.SOUTH_AMERICA,
  },
  {
    name: "Haiti",
    dialCode: "+509",
    code: "HT",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Honduras",
    dialCode: "+504",
    code: "HN",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Hong Kong",
    dialCode: "+852",
    code: "HK",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Hungary",
    dialCode: "+36",
    code: "HU",
    visited: true,
    year: 2022,
    posts: [],
    continent: Continent.EUROPE,
    introduction:
      "Hungary is a beautiful country located in central Europe, known for its stunning architecture, rich history, and vibrant culture. Visitors to Hungary can explore the charming streets of Budapest, a city famous for its thermal baths, historic landmarks, and delicious cuisine. The country is also home to a variety of ancient castles, including the stunning Buda Castle, as well as natural wonders like the Lake Balaton and the Danube Bend. Hungarian cuisine is hearty and delicious, with traditional dishes like goulash, chimney cake, and wine all on offer. With its rich history, stunning landscapes, and warm hospitality, Hungary is a destination that's sure to leave a lasting impression on any traveler.",
  },
  {
    name: "Iceland",
    dialCode: "+354",
    code: "IS",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "India",
    dialCode: "+91",
    code: "IN",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Indonesia",
    dialCode: "+62",
    code: "ID",
    visited: true,
    year: 2022,
    posts: [],
    continent: Continent.ASIA,
    introduction:
      "Indonesia is a diverse and fascinating country located in Southeast Asia, known for its beautiful beaches, tropical landscapes, and unique culture. Visitors to Indonesia can explore the bustling capital city of Jakarta, or the historic city of Yogyakarta, home to the famous Borobudur temple. The country is also home to a variety of natural wonders, including the stunning rice terraces of Bali, the beautiful beaches of Lombok and Gili Islands, and the breathtaking volcanoes of Java. Indonesian cuisine is delicious and varied, with traditional dishes like nasi goreng, sate, and rendang all on offer. With its rich culture, stunning landscapes, and warm hospitality, Indonesia is a destination that's sure to enchant any traveler.",
  },
  {
    name: "Iran",
    dialCode: "+98",
    code: "IR",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Iraq",
    dialCode: "+964",
    code: "IQ",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Ireland",
    dialCode: "+353",
    code: "IE",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Israel",
    dialCode: "+972",
    code: "IL",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Italy",
    dialCode: "+39",
    code: "IT",
    visited: true,
    year: 2013,
    posts: [],
    continent: Continent.EUROPE,
    introduction:
      "Italy is a beautiful country located in southern Europe, known for its stunning architecture, rich history, and delicious cuisine. Visitors to Italy can explore the ancient ruins of Rome, the charming streets of Florence, and the romantic canals of Venice. The country is also home to a variety of natural wonders, including the breathtaking Amalfi Coast and the stunning Dolomite Mountains. Italian cuisine is world-renowned, with traditional dishes like pizza, pasta, and gelato all on offer. With its rich history, stunning landscapes, and warm hospitality, Italy is a destination that's sure to delight any traveler.",
  },
  {
    name: "Jamaica",
    dialCode: "+1876",
    code: "JM",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Japan",
    dialCode: "+81",
    code: "JP",
    visited: true,
    year: 2019,
    posts: [],
    continent: Continent.ASIA,
    introduction:
      "Japan is a fascinating country located in East Asia, known for its unique culture, stunning scenery, and delicious cuisine. Visitors to Japan can explore the bright lights of Tokyo, the historic streets of Kyoto, and the serene gardens of Hiroshima. The country is also home to a variety of natural wonders, including Mount Fuji and the cherry blossom trees that bloom in the spring. Japanese cuisine is diverse and delicious, with traditional dishes like sushi, ramen, and tempura all on offer. With its rich history, stunning landscapes, and warm hospitality, Japan is a destination that's sure to leave a lasting impression on any traveler.",
  },
  {
    name: "Jordan",
    dialCode: "+962",
    code: "JO",
    visited: true,
    year: 2022,
    posts: [],
    continent: Continent.ASIA,
    introduction:
      "Jordan is a beautiful country located in the heart of the Middle East, known for its ancient history, stunning landscapes, and warm hospitality. Visitors to Jordan can explore the historic city of Petra, one of the New Seven Wonders of the World, or float in the salty waters of the Dead Sea. The country is also home to a variety of natural wonders, including the stunning Wadi Rum desert and the breathtaking views from Mount Nebo. Jordanian cuisine is delicious and varied, with traditional dishes like mansaf, falafel, and hummus all on offer. With its rich history, stunning landscapes, and warm hospitality, Jordan is a destination that's sure to enchant any traveler.",
  },
  {
    name: "Kazakhstan",
    dialCode: "+77",
    code: "KZ",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Kenya",
    dialCode: "+254",
    code: "KE",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Kiribati",
    dialCode: "+686",
    code: "KI",
    visited: false,
    posts: [],
    continent: Continent.OCEANIA,
  },
  {
    name: "North-Korea",
    dialCode: "+850",
    code: "KP",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "South-Korea",
    dialCode: "+82",
    code: "KR",
    visited: true,
    year: 2019,
    posts: [],
    continent: Continent.ASIA,
    introduction:
      "South Korea is a beautiful country located in East Asia, known for its rich culture, modern cities, and delicious cuisine. Visitors to South Korea can explore the bustling streets of Seoul, the historic sites of Gyeongju, and the beautiful beaches of Jeju Island. The country is also home to a variety of natural wonders, including the stunning Seoraksan National Park and the beautiful Nami Island. Korean cuisine is delicious and diverse, with traditional dishes like kimchi, bibimbap, and bulgogi all on offer. With its rich culture, stunning landscapes, and warm hospitality, South Korea is a destination that's sure to leave a lasting impression on any traveler.",
  },
  {
    name: "Kuwait",
    dialCode: "+965",
    code: "KW",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Kyrgyzstan",
    dialCode: "+996",
    code: "KG",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Laos",
    dialCode: "+856",
    code: "LA",
    visited: true,
    year: 2019,
    posts: [],
    continent: Continent.ASIA,
    introduction:
      "Laos is a beautiful country located in Southeast Asia, known for its stunning natural scenery, rich culture, and laid-back lifestyle. Visitors to Laos can explore the historic streets of Luang Prabang, cruise down the Mekong River, and hike in the lush jungles of the Bolaven Plateau. The country is also home to a variety of natural wonders, including the stunning Kuang Si Waterfall and the serene Mekong Delta. Laotian cuisine is delicious and unique, with traditional dishes like laap, sticky rice, and papaya salad all on offer. With its stunning landscapes, rich culture, and warm hospitality, Laos is a destination that's sure to enchant any traveler.",
  },
  {
    name: "Latvia",
    dialCode: "+371",
    code: "LV",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Lebanon",
    dialCode: "+961",
    code: "LB",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Lesotho",
    dialCode: "+266",
    code: "LS",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Liberia",
    dialCode: "+231",
    code: "LR",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Libya",
    dialCode: "+218",
    code: "LY",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Liechtenstein",
    dialCode: "+423",
    code: "LI",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Lithuania",
    dialCode: "+370",
    code: "LT",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Luxembourg",
    dialCode: "+352",
    code: "LU",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Macao",
    dialCode: "+853",
    code: "MO",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Macedonia",
    dialCode: "+389",
    code: "MK",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Madagascar",
    dialCode: "+261",
    code: "MG",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Malawi",
    dialCode: "+265",
    code: "MW",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Malaysia",
    dialCode: "+60",
    code: "MY",
    visited: true,
    year: 2022,
    posts: [],
    continent: Continent.ASIA,
    introduction:
      "Malaysia is a beautiful country located in Southeast Asia, known for its diverse culture, stunning natural scenery, and delicious cuisine. Visitors to Malaysia can explore the vibrant streets of Kuala Lumpur, the historic city of Malacca, and the beautiful beaches of Langkawi Island. The country is also home to a variety of natural wonders, including the stunning Taman Negara National Park and the breathtaking Cameron Highlands. Malaysian cuisine is delicious and diverse, with traditional dishes like nasi lemak, satay, and laksa all on offer. With its diverse culture, stunning landscapes, and warm hospitality, Malaysia is a destination that's sure to leave a lasting impression on any traveler.",
  },
  {
    name: "Maldives",
    dialCode: "+960",
    code: "MV",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Mali",
    dialCode: "+223",
    code: "ML",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Malta",
    dialCode: "+356",
    code: "MT",
    visited: true,
    year: 2022,
    posts: [],
    continent: Continent.EUROPE,
    introduction:
      "Malta is a beautiful island nation located in the Mediterranean Sea, known for its rich history, stunning natural scenery, and warm hospitality. Visitors to Malta can explore the historic streets of Valletta, the ancient temples of Hagar Qim, and the beautiful beaches of Comino Island. The country is also home to a variety of natural wonders, including the stunning Blue Lagoon and the breathtaking Dingli Cliffs. Maltese cuisine is delicious and unique, with traditional dishes like pastizzi, rabbit stew, and fresh seafood all on offer. With its rich history, stunning landscapes, and warm hospitality, Malta is a destination that's sure to enchant any traveler.",
  },
  {
    name: "Marshall Islands",
    dialCode: "+692",
    code: "MH",
    visited: false,
    posts: [],
    continent: Continent.OCEANIA,
  },
  {
    name: "Martinique",
    dialCode: "+596",
    code: "MQ",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Mauritania",
    dialCode: "+222",
    code: "MR",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Mauritius",
    dialCode: "+230",
    code: "MU",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Mexico",
    dialCode: "+52",
    code: "MX",
    visited: true,
    year: 2022,
    posts: [],
    continent: Continent.NORTH_AMERICA,
    introduction:
      "Mexico is a beautiful country located in North America, known for its vibrant culture, stunning natural scenery, and delicious cuisine. Visitors to Mexico can explore the historic streets of Mexico City, the ancient ruins of Chichen Itza, and the beautiful beaches of Cancun. The country is also home to a variety of natural wonders, including the stunning Copper Canyon and the breathtaking cenotes of the Yucatan Peninsula. Mexican cuisine is delicious and varied, with traditional dishes like tacos, enchiladas, and guacamole all on offer. With its vibrant culture, stunning landscapes, and warm hospitality, Mexico is a destination that's sure to leave a lasting impression on any traveler.",
  },
  {
    name: "Micronesia",
    dialCode: "+691",
    code: "FM",
    visited: false,
    posts: [],
    continent: Continent.OCEANIA,
  },
  {
    name: "Moldova",
    dialCode: "+373",
    code: "MD",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Monaco",
    dialCode: "+377",
    code: "MC",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Mongolia",
    dialCode: "+976",
    code: "MN",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Montenegro",
    dialCode: "+382",
    code: "ME",
    visited: true,
    year: 2022,
    posts: [],
    continent: Continent.EUROPE,
    introduction:
      "Montenegro is a beautiful country located in Southeastern Europe, known for its stunning natural scenery, rich history, and warm hospitality. Visitors to Montenegro can explore the historic streets of Kotor, the beautiful beaches of Budva, and the breathtaking Durmitor National Park. The country is also home to a variety of natural wonders, including the stunning Bay of Kotor and the breathtaking Tara River Canyon. Montenegrin cuisine is delicious and unique, with traditional dishes like cicvara, priganice, and fresh seafood all on offer. With its stunning landscapes, rich history, and warm hospitality, Montenegro is a destination that's sure to enchant any traveler.",
  },
  {
    name: "Morocco",
    dialCode: "+212",
    code: "MA",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Mozambique",
    dialCode: "+258",
    code: "MZ",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Myanmar",
    dialCode: "+95",
    code: "MM",
    visited: true,
    year: 2019,
    posts: [],
    continent: Continent.ASIA,
    introduction:
      "Myanmar, also known as Burma, is a beautiful country located in Southeast Asia, known for its rich culture, stunning natural scenery, and warm hospitality. Visitors to Myanmar can explore the ancient temples of Bagan, the vibrant streets of Yangon, and the beautiful beaches of Ngapali. The country is also home to a variety of natural wonders, including the stunning Inle Lake and the breathtaking Golden Rock. Burmese cuisine is delicious and varied, with traditional dishes like mohinga, tea leaf salad, and Shan-style tofu noodles all on offer. With its rich culture, stunning landscapes, and warm hospitality, Myanmar is a destination that's sure to leave a lasting impression on any traveler.",
  },
  {
    name: "Namibia",
    dialCode: "+264",
    code: "NA",
    visited: false,
    year: 2019,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Nauru",
    dialCode: "+674",
    code: "NR",
    visited: false,
    posts: [],
    continent: Continent.OCEANIA,
  },
  {
    name: "Nepal",
    dialCode: "+977",
    code: "NP",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Netherlands",
    dialCode: "+31",
    code: "NL",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "New-Caledonia",
    dialCode: "+687",
    code: "NC",
    visited: false,
    posts: [],
    continent: Continent.OCEANIA,
  },
  {
    name: "New-Zealand",
    dialCode: "+64",
    code: "NZ",
    visited: true,
    year: 2017,
    posts: [],
    continent: Continent.OCEANIA,
    introduction:
      "New Zealand is a beautiful island nation located in the South Pacific, known for its stunning natural scenery, adventurous spirit, and warm hospitality. Visitors to New Zealand can explore the majestic fjords of Milford Sound, the breathtaking mountains of Queenstown, and the stunning beaches of the Bay of Islands. The country is also home to a variety of natural wonders, including the stunning Tongariro National Park and the breathtaking Franz Josef Glacier. New Zealand cuisine is delicious and varied, with traditional dishes like meat pies, fish and chips, and pavlova all on offer. With its stunning landscapes, adventurous spirit, and warm hospitality, New Zealand is a destination that's sure to enchant any traveler.",
  },
  {
    name: "Nicaragua",
    dialCode: "+505",
    code: "NI",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Niger",
    dialCode: "+227",
    code: "NE",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Nigeria",
    dialCode: "+234",
    code: "NG",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Norway",
    dialCode: "+47",
    code: "NO",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Oman",
    dialCode: "+968",
    code: "OM",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Pakistan",
    dialCode: "+92",
    code: "PK",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Palau",
    dialCode: "+680",
    code: "PW",
    visited: false,
    posts: [],
    continent: Continent.OCEANIA,
  },
  {
    name: "Palestine",
    dialCode: "+970",
    code: "PS",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Panama",
    dialCode: "+507",
    code: "PA",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Papua New Guinea",
    dialCode: "+675",
    code: "PG",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Paraguay",
    dialCode: "+595",
    code: "PY",
    visited: false,
    posts: [],
    continent: Continent.SOUTH_AMERICA,
  },
  {
    name: "Peru",
    dialCode: "+51",
    code: "PE",
    visited: false,
    posts: [],
    continent: Continent.SOUTH_AMERICA,
  },
  {
    name: "Philippines",
    dialCode: "+63",
    code: "PH",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Poland",
    dialCode: "+48",
    code: "PL",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Portugal",
    dialCode: "+351",
    code: "PT",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Puerto Rico",
    dialCode: "+1939",
    code: "PR",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Qatar",
    dialCode: "+974",
    code: "QA",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Romania",
    dialCode: "+40",
    code: "RO",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Russia",
    dialCode: "+7",
    code: "RU",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Rwanda",
    dialCode: "+250",
    code: "RW",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Reunion",
    dialCode: "+262",
    code: "RE",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Saint Barthelemy",
    dialCode: "+590",
    code: "BL",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Saint Kitts and Nevis",
    dialCode: "+1869",
    code: "KN",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Saint Lucia",
    dialCode: "+1758",
    code: "LC",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Saint Martin",
    dialCode: "+590",
    code: "MF",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Saint Pierre and Miquelon",
    dialCode: "+508",
    code: "PM",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Saint Vincent and the Grenadines",
    dialCode: "+1784",
    code: "VC",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Samoa",
    dialCode: "+685",
    code: "WS",
    visited: false,
    posts: [],
    continent: Continent.OCEANIA,
  },
  {
    name: "San Marino",
    dialCode: "+378",
    code: "SM",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Sao Tome and Principe",
    dialCode: "+239",
    code: "ST",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Saudi Arabia",
    dialCode: "+966",
    code: "SA",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Senegal",
    dialCode: "+221",
    code: "SN",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Serbia",
    dialCode: "+381",
    code: "RS",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Seychelles",
    dialCode: "+248",
    code: "SC",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Sierra Leone",
    dialCode: "+232",
    code: "SL",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Singapore",
    dialCode: "+65",
    code: "SG",
    visited: true,
    year: 2023,
    posts: [],
    continent: Continent.ASIA,
    introduction:
      "Singapore is a vibrant city-state located in Southeast Asia, known for its modern skyline, diverse culture, and delicious cuisine. Visitors to Singapore can explore the vibrant neighborhoods of Chinatown, Little India, and Arab Street, as well as the stunning Gardens by the Bay and Marina Bay Sands. The country is also home to a variety of cultural and historical attractions, including the iconic Merlion statue and the beautiful Buddhist temple of Thian Hock Keng. Singaporean cuisine is delicious and varied, with traditional dishes like laksa, chili crab, and Hainanese chicken rice all on offer. With its modern skyline, rich culture, and delicious cuisine, Singapore is a destination that's sure to delight any traveler.",
  },
  {
    name: "Slovakia",
    dialCode: "+421",
    code: "SK",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Slovenia",
    dialCode: "+386",
    code: "SI",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Solomon Islands",
    dialCode: "+677",
    code: "SB",
    visited: false,
    posts: [],
    continent: Continent.OCEANIA,
  },
  {
    name: "Somalia",
    dialCode: "+252",
    code: "SO",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "South Africa",
    dialCode: "+27",
    code: "ZA",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "South Sudan",
    dialCode: "+211",
    code: "SS",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Spain",
    dialCode: "+34",
    code: "ES",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Sri Lanka",
    dialCode: "+94",
    code: "LK",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Sudan",
    dialCode: "+249",
    code: "SD",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Suriname",
    dialCode: "+597",
    code: "SR",
    visited: false,
    posts: [],
    continent: Continent.SOUTH_AMERICA,
  },
  {
    name: "Svalbard and Jan Mayen",
    dialCode: "+47",
    code: "SJ",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Swaziland",
    dialCode: "+268",
    code: "SZ",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Sweden",
    dialCode: "+46",
    code: "SE",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Switzerland",
    dialCode: "+41",
    code: "CH",
    visited: true,
    year: 2022,
    posts: ["post-1", "post-2", "post-3", "post-5"],
    continent: Continent.EUROPE,
    introduction:
      "Switzerland is a beautiful country located in Central Europe, known for its stunning Alpine scenery, rich culture, and world-class skiing. Visitors to Switzerland can explore the charming cities of Zurich and Geneva, as well as the breathtaking mountain landscapes of the Swiss Alps. The country is also home to a variety of cultural and historical attractions, including the iconic Matterhorn mountain and the stunning Rhine Falls. Swiss cuisine is delicious and varied, with traditional dishes like fondue, raclette, and rosti all on offer. With its stunning landscapes, rich culture, and delicious cuisine, Switzerland is a destination that's sure to enchant any traveler.",
  },
  {
    name: "Syria",
    dialCode: "+963",
    code: "SY",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Taiwan",
    dialCode: "+886",
    code: "TW",
    visited: true,
    year: 2018,
    posts: [],
    continent: Continent.ASIA,
    introduction:
      "Taiwan is a beautiful island nation located in East Asia, known for its vibrant culture, stunning natural scenery, and delicious cuisine. Visitors to Taiwan can explore the vibrant streets of Taipei, the beautiful Sun Moon Lake, and the breathtaking Taroko Gorge. The country is also home to a variety of cultural and historical attractions, including the iconic Taipei 101 skyscraper and the beautiful Chiang Kai-shek Memorial Hall. Taiwanese cuisine is delicious and varied, with traditional dishes like beef noodle soup, stinky tofu, and bubble tea all on offer. With its vibrant culture, stunning landscapes, and delicious cuisine, Taiwan is a destination that's sure to leave a lasting impression on any traveler.",
  },
  {
    name: "Tajikistan",
    dialCode: "+992",
    code: "TJ",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Tanzania",
    dialCode: "+255",
    code: "TZ",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Thailand",
    dialCode: "+66",
    code: "TH",
    visited: true,
    year: 2022,
    posts: [],
    continent: Continent.ASIA,
    introduction:
      "Thailand is a vibrant country located in Southeast Asia, known for its beautiful beaches, ancient temples, and delicious cuisine. Visitors to Thailand can explore the bustling capital city of Bangkok, as well as the stunning islands of Phuket and Koh Samui. The country is also home to a variety of cultural and historical attractions, including the iconic Wat Phra Kaew temple and the beautiful Grand Palace. Thai cuisine is delicious and varied, with traditional dishes like pad Thai, green curry, and tom yum soup all on offer. With its beautiful beaches, rich culture, and delicious cuisine, Thailand is a destination that's sure to enchant any traveler.",
  },
  {
    name: "Timor-Leste",
    dialCode: "+670",
    code: "TL",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Togo",
    dialCode: "+228",
    code: "TG",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Tonga",
    dialCode: "+676",
    code: "TO",
    visited: false,
    posts: [],
    continent: Continent.OCEANIA,
  },
  {
    name: "Trinidad and Tobago",
    dialCode: "+1868",
    code: "TT",
    visited: false,
    posts: [],
    continent: Continent.NORTH_AMERICA,
  },
  {
    name: "Tunisia",
    dialCode: "+216",
    code: "TN",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Turkey",
    dialCode: "+90",
    code: "TR",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "Turkmenistan",
    dialCode: "+993",
    code: "TM",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Tuvalu",
    dialCode: "+688",
    code: "TV",
    visited: false,
    posts: [],
    continent: Continent.OCEANIA,
  },
  {
    name: "Uganda",
    dialCode: "+256",
    code: "UG",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Ukraine",
    dialCode: "+380",
    code: "UA",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "UAE",
    dialCode: "+971",
    code: "AE",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "United-Kingdom",
    dialCode: "+44",
    code: "GB",
    visited: false,
    posts: [],
    continent: Continent.EUROPE,
  },
  {
    name: "USA",
    dialCode: "+1",
    code: "US",
    visited: true,
    year: 2022,
    posts: [],
    continent: Continent.NORTH_AMERICA,
    introduction:
      "The United States of America is a vast and diverse country, known for its iconic landmarks, beautiful national parks, and diverse culture. Visitors to the USA can explore the bustling cities of New York, Los Angeles, and Chicago, as well as the breathtaking landscapes of Yellowstone National Park and the Grand Canyon. The country is also home to a variety of cultural and historical attractions, including the iconic Statue of Liberty and the beautiful White House. American cuisine is delicious and varied, with traditional dishes like burgers, hot dogs, and apple pie all on offer. With its diverse culture, stunning landscapes, and delicious cuisine, the USA is a destination that's sure to inspire any traveler.",
  },
  {
    name: "Uruguay",
    dialCode: "+598",
    code: "UY",
    visited: false,
    posts: [],
    continent: Continent.SOUTH_AMERICA,
  },
  {
    name: "Uzbekistan",
    dialCode: "+998",
    code: "UZ",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Vanuatu",
    dialCode: "+678",
    code: "VU",
    visited: false,
    posts: [],
    continent: Continent.OCEANIA,
  },
  {
    name: "Venezuela",
    dialCode: "+58",
    code: "VE",
    visited: false,
    posts: [],
    continent: Continent.SOUTH_AMERICA,
  },
  {
    name: "Vietnam",
    dialCode: "+84",
    code: "VN",
    visited: true,
    year: 2020,
    posts: [],
    continent: Continent.ASIA,
    introduction:
      "Vietnam is a beautiful country located in Southeast Asia, known for its stunning natural scenery, rich culture, and delicious cuisine. Visitors to Vietnam can explore the bustling city of Ho Chi Minh, as well as the stunning landscapes of Halong Bay and the Mekong Delta. The country is also home to a variety of cultural and historical attractions, including the iconic Hoan Kiem Lake and the beautiful Hue Citadel. Vietnamese cuisine is delicious and varied, with traditional dishes like pho, banh mi, and fresh spring rolls all on offer. With its stunning landscapes, rich culture, and delicious cuisine, Vietnam is a destination that's sure to captivate any traveler.",
  },
  {
    name: "Yemen",
    dialCode: "+967",
    code: "YE",
    visited: false,
    posts: [],
    continent: Continent.ASIA,
  },
  {
    name: "Zambia",
    dialCode: "+260",
    code: "ZM",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
  {
    name: "Zimbabwe",
    dialCode: "+263",
    code: "ZW",
    visited: false,
    posts: [],
    continent: Continent.AFRICA,
  },
];
