import { Country } from "@/interfaces/Country.interface";

export const countriesData: Country[] = [
  {
    name: "Afghanistan",
    dialCode: "+93",
    code: "AF",
    visited: false,
    posts: [],
  },
  {
    name: "Aland Islands",
    dialCode: "+358",
    code: "AX",
    visited: false,
    posts: [],
  },
  {
    name: "Albania",
    dialCode: "+355",
    code: "AL",
    visited: true,
    year: 2022,
    posts: ["post-1", "post-2", "post-3"],
  },
  {
    name: "Algeria",
    dialCode: "+213",
    code: "DZ",
    visited: false,
    posts: [],
  },
  {
    name: "AmericanSamoa",
    dialCode: "+1684",
    code: "AS",
    visited: false,
    posts: [],
  },
  {
    name: "Andorra",
    dialCode: "+376",
    code: "AD",
    visited: false,
    posts: [],
  },
  {
    name: "Angola",
    dialCode: "+244",
    code: "AO",
    visited: false,
    posts: [],
  },
  {
    name: "Anguilla",
    dialCode: "+1264",
    code: "AI",
    visited: false,
    posts: [],
  },
  {
    name: "Antarctica",
    dialCode: "+672",
    code: "AQ",
    visited: false,
    posts: [],
  },
  {
    name: "Antigua and Barbuda",
    dialCode: "+1268",
    code: "AG",
    visited: false,
    posts: [],
  },
  {
    name: "Argentina",
    dialCode: "+54",
    code: "AR",
    visited: false,
    posts: [],
  },
  {
    name: "Armenia",
    dialCode: "+374",
    code: "AM",
    visited: false,
    posts: [],
  },
  {
    name: "Aruba",
    dialCode: "+297",
    code: "AW",
    visited: false,
    posts: [],
  },
  {
    name: "Australia",
    dialCode: "+61",
    code: "AU",
    visited: true,
    posts: [],
  },
  {
    name: "Austria",
    dialCode: "+43",
    code: "AT",
    visited: false,
    posts: [],
  },
  {
    name: "Azerbaijan",
    dialCode: "+994",
    code: "AZ",
    visited: false,
    posts: [],
  },
  {
    name: "Bahamas",
    dialCode: "+1242",
    code: "BS",
    visited: false,
    posts: [],
  },
  {
    name: "Bahrain",
    dialCode: "+973",
    code: "BH",
    visited: false,
    posts: [],
  },
  {
    name: "Bangladesh",
    dialCode: "+880",
    code: "BD",
    visited: false,
    posts: [],
  },
  {
    name: "Barbados",
    dialCode: "+1246",
    code: "BB",
    visited: false,
    posts: [],
  },
  {
    name: "Belarus",
    dialCode: "+375",
    code: "BY",
    visited: false,
    posts: [],
  },
  {
    name: "Belgium",
    dialCode: "+32",
    code: "BE",
    visited: false,
    posts: [],
  },
  {
    name: "Belize",
    dialCode: "+501",
    code: "BZ",
    visited: false,
    posts: [],
  },
  {
    name: "Benin",
    dialCode: "+229",
    code: "BJ",
    visited: false,
    posts: [],
  },
  {
    name: "Bermuda",
    dialCode: "+1441",
    code: "BM",
    visited: false,
    posts: [],
  },
  {
    name: "Bhutan",
    dialCode: "+975",
    code: "BT",
    visited: false,
    posts: [],
  },
  {
    name: "Bolivia, Plurinational State of",
    dialCode: "+591",
    code: "BO",
    visited: false,
    posts: [],
  },
  {
    name: "Bosnia and Herzegovina",
    dialCode: "+387",
    code: "BA",
    visited: true,
    year: 2022,
    posts: [],
  },
  {
    name: "Botswana",
    dialCode: "+267",
    code: "BW",
    visited: false,
    posts: [],
  },
  {
    name: "Brazil",
    dialCode: "+55",
    code: "BR",
    visited: false,
    posts: [],
  },
  {
    name: "British Indian Ocean Territory",
    dialCode: "+246",
    code: "IO",
    visited: false,
    posts: [],
  },
  {
    name: "Brunei",
    dialCode: "+673",
    code: "BN",
    visited: true,
    year: 2016,
    posts: [],
  },
  {
    name: "Bulgaria",
    dialCode: "+359",
    code: "BG",
    visited: false,
    posts: [],
  },
  {
    name: "Burkina Faso",
    dialCode: "+226",
    code: "BF",
    visited: false,
    posts: [],
  },
  {
    name: "Burundi",
    dialCode: "+257",
    code: "BI",
    visited: false,
    posts: [],
  },
  {
    name: "Cambodia",
    dialCode: "+855",
    code: "KH",
    visited: true,
    year: 2019,
    posts: [],
  },
  {
    name: "Cameroon",
    dialCode: "+237",
    code: "CM",
    visited: false,
    posts: [],
  },
  {
    name: "Canada",
    dialCode: "+1",
    code: "CA",
    visited: false,
    posts: [],
  },
  {
    name: "Cape Verde",
    dialCode: "+238",
    code: "CV",
    visited: false,
    posts: [],
  },
  {
    name: "Cayman Islands",
    dialCode: "+ 345",
    code: "KY",
    visited: false,
    posts: [],
  },
  {
    name: "Central African Republic",
    dialCode: "+236",
    code: "CF",
    visited: false,
    posts: [],
  },
  {
    name: "Chad",
    dialCode: "+235",
    code: "TD",
    visited: false,
    posts: [],
  },
  {
    name: "Chile",
    dialCode: "+56",
    code: "CL",
    visited: false,
    posts: [],
  },
  {
    name: "China",
    dialCode: "+86",
    code: "CN",
    visited: true,
    year: 2019,
    posts: [],
  },
  {
    name: "Christmas Island",
    dialCode: "+61",
    code: "CX",
    visited: false,
    posts: [],
  },
  {
    name: "Cocos (Keeling) Islands",
    dialCode: "+61",
    code: "CC",
    visited: false,
    posts: [],
  },
  {
    name: "Colombia",
    dialCode: "+57",
    code: "CO",
    visited: false,
    posts: [],
  },
  {
    name: "Comoros",
    dialCode: "+269",
    code: "KM",
    visited: false,
    posts: [],
  },
  {
    name: "Congo",
    dialCode: "+242",
    code: "CG",
    visited: false,
    posts: [],
  },
  {
    name: "Congo, The Democratic Republic of the Congo",
    dialCode: "+243",
    code: "CD",
    visited: false,
    posts: [],
  },
  {
    name: "Cook Islands",
    dialCode: "+682",
    code: "CK",
    visited: false,
    posts: [],
  },
  {
    name: "Costa Rica",
    dialCode: "+506",
    code: "CR",
    visited: false,
    posts: [],
  },
  {
    name: "Cote d'Ivoire",
    dialCode: "+225",
    code: "CI",
    visited: false,
    posts: [],
  },
  {
    name: "Croatia",
    dialCode: "+385",
    code: "HR",
    visited: true,
    year: 2022,
    posts: [],
  },
  {
    name: "Cuba",
    dialCode: "+53",
    code: "CU",
    visited: false,
    posts: [],
  },
  {
    name: "Cyprus",
    dialCode: "+357",
    code: "CY",
    visited: false,
    posts: [],
  },
  {
    name: "Czech Republic",
    dialCode: "+420",
    code: "CZ",
    visited: true,
    year: 2022,
    posts: [],
  },
  {
    name: "Denmark",
    dialCode: "+45",
    code: "DK",
    visited: false,
    posts: [],
  },
  {
    name: "Djibouti",
    dialCode: "+253",
    code: "DJ",
    visited: false,
    posts: [],
  },
  {
    name: "Dominica",
    dialCode: "+1767",
    code: "DM",
    visited: false,
    posts: [],
  },
  {
    name: "Dominican Republic",
    dialCode: "+1849",
    code: "DO",
    visited: false,
    posts: [],
  },
  {
    name: "Ecuador",
    dialCode: "+593",
    code: "EC",
    visited: false,
    posts: [],
  },
  {
    name: "Egypt",
    dialCode: "+20",
    code: "EG",
    visited: false,
    posts: [],
  },
  {
    name: "El Salvador",
    dialCode: "+503",
    code: "SV",
    visited: false,
    posts: [],
  },
  {
    name: "Equatorial Guinea",
    dialCode: "+240",
    code: "GQ",
    visited: false,
    posts: [],
  },
  {
    name: "Eritrea",
    dialCode: "+291",
    code: "ER",
    visited: false,
    posts: [],
  },
  {
    name: "Estonia",
    dialCode: "+372",
    code: "EE",
    visited: false,
    posts: [],
  },
  {
    name: "Ethiopia",
    dialCode: "+251",
    code: "ET",
    visited: false,
    posts: [],
  },
  {
    name: "Falkland Islands (Malvinas)",
    dialCode: "+500",
    code: "FK",
    visited: false,
    posts: [],
  },
  {
    name: "Faroe Islands",
    dialCode: "+298",
    code: "FO",
    visited: false,
    posts: [],
  },
  {
    name: "Fiji",
    dialCode: "+679",
    code: "FJ",
    visited: false,
    posts: [],
  },
  {
    name: "Finland",
    dialCode: "+358",
    code: "FI",
    visited: false,
    posts: [],
  },
  {
    name: "France",
    dialCode: "+33",
    code: "FR",
    visited: false,
    posts: [],
  },
  {
    name: "French Guiana",
    dialCode: "+594",
    code: "GF",
    visited: false,
    posts: [],
  },
  {
    name: "French Polynesia",
    dialCode: "+689",
    code: "PF",
    visited: false,
    posts: [],
  },
  {
    name: "Gabon",
    dialCode: "+241",
    code: "GA",
    visited: false,
    posts: [],
  },
  {
    name: "Gambia",
    dialCode: "+220",
    code: "GM",
    visited: false,
    posts: [],
  },
  {
    name: "Georgia",
    dialCode: "+995",
    code: "GE",
    visited: false,
    posts: [],
  },
  {
    name: "Germany",
    dialCode: "+49",
    code: "DE",
    visited: true,
    year: 2022,
    posts: [],
  },
  {
    name: "Ghana",
    dialCode: "+233",
    code: "GH",
    visited: false,
    posts: [],
  },
  {
    name: "Gibraltar",
    dialCode: "+350",
    code: "GI",
    visited: false,
    posts: [],
  },
  {
    name: "Greece",
    dialCode: "+30",
    code: "GR",
    visited: false,
    posts: [],
  },
  {
    name: "Greenland",
    dialCode: "+299",
    code: "GL",
    visited: false,
    posts: [],
  },
  {
    name: "Grenada",
    dialCode: "+1473",
    code: "GD",
    visited: false,
    posts: [],
  },
  {
    name: "Guadeloupe",
    dialCode: "+590",
    code: "GP",
    visited: false,
    posts: [],
  },
  {
    name: "Guam",
    dialCode: "+1671",
    code: "GU",
    visited: false,
    posts: [],
  },
  {
    name: "Guatemala",
    dialCode: "+502",
    code: "GT",
    visited: false,
    posts: [],
  },
  {
    name: "Guernsey",
    dialCode: "+44",
    code: "GG",
    visited: false,
    posts: [],
  },
  {
    name: "Guinea",
    dialCode: "+224",
    code: "GN",
    visited: false,
    posts: [],
  },
  {
    name: "Guinea-Bissau",
    dialCode: "+245",
    code: "GW",
    visited: false,
    posts: [],
  },
  {
    name: "Guyana",
    dialCode: "+595",
    code: "GY",
    visited: false,
    posts: [],
  },
  {
    name: "Haiti",
    dialCode: "+509",
    code: "HT",
    visited: false,
    posts: [],
  },
  {
    name: "Holy See (Vatican City State)",
    dialCode: "+379",
    code: "VA",
    visited: false,
    posts: [],
  },
  {
    name: "Honduras",
    dialCode: "+504",
    code: "HN",
    visited: false,
    posts: [],
  },
  {
    name: "Hong Kong",
    dialCode: "+852",
    code: "HK",
    visited: false,
    posts: [],
  },
  {
    name: "Hungary",
    dialCode: "+36",
    code: "HU",
    visited: true,
    year: 2022,
    posts: [],
  },
  {
    name: "Iceland",
    dialCode: "+354",
    code: "IS",
    visited: false,
    posts: [],
  },
  {
    name: "India",
    dialCode: "+91",
    code: "IN",
    visited: false,
    posts: [],
  },
  {
    name: "Indonesia",
    dialCode: "+62",
    code: "ID",
    visited: true,
    year: 2022,
    posts: [],
  },
  {
    name: "Iran, Islamic Republic of Persian Gulf",
    dialCode: "+98",
    code: "IR",
    visited: false,
    posts: [],
  },
  {
    name: "Iraq",
    dialCode: "+964",
    code: "IQ",
    visited: false,
    posts: [],
  },
  {
    name: "Ireland",
    dialCode: "+353",
    code: "IE",
    visited: false,
    posts: [],
  },
  {
    name: "Isle of Man",
    dialCode: "+44",
    code: "IM",
    visited: false,
    posts: [],
  },
  {
    name: "Israel",
    dialCode: "+972",
    code: "IL",
    visited: false,
    posts: [],
  },
  {
    name: "Italy",
    dialCode: "+39",
    code: "IT",
    visited: true,
    year: 2013,
    posts: [],
  },
  {
    name: "Jamaica",
    dialCode: "+1876",
    code: "JM",
    visited: false,
    posts: [],
  },
  {
    name: "Japan",
    dialCode: "+81",
    code: "JP",
    visited: true,
    year: 2019,
    posts: [],
  },
  {
    name: "Jersey",
    dialCode: "+44",
    code: "JE",
    visited: false,
    posts: [],
  },
  {
    name: "Jordan",
    dialCode: "+962",
    code: "JO",
    visited: true,
    year: 2022,
    posts: [],
  },
  {
    name: "Kazakhstan",
    dialCode: "+77",
    code: "KZ",
    visited: false,
    posts: [],
  },
  {
    name: "Kenya",
    dialCode: "+254",
    code: "KE",
    visited: false,
    posts: [],
  },
  {
    name: "Kiribati",
    dialCode: "+686",
    code: "KI",
    visited: false,
    posts: [],
  },
  {
    name: "North Korea",
    dialCode: "+850",
    code: "KP",
    visited: false,
    posts: [],
  },
  {
    name: "South Korea",
    dialCode: "+82",
    code: "KR",
    visited: true,
    year: 2019,
    posts: [],
  },
  {
    name: "Kuwait",
    dialCode: "+965",
    code: "KW",
    visited: false,
    posts: [],
  },
  {
    name: "Kyrgyzstan",
    dialCode: "+996",
    code: "KG",
    visited: false,
    posts: [],
  },
  {
    name: "Laos",
    dialCode: "+856",
    code: "LA",
    visited: true,
    year: 2019,
    posts: [],
  },
  {
    name: "Latvia",
    dialCode: "+371",
    code: "LV",
    visited: false,
    posts: [],
  },
  {
    name: "Lebanon",
    dialCode: "+961",
    code: "LB",
    visited: false,
    posts: [],
  },
  {
    name: "Lesotho",
    dialCode: "+266",
    code: "LS",
    visited: false,
    posts: [],
  },
  {
    name: "Liberia",
    dialCode: "+231",
    code: "LR",
    visited: false,
    posts: [],
  },
  {
    name: "Libyan Arab Jamahiriya",
    dialCode: "+218",
    code: "LY",
    visited: false,
    posts: [],
  },
  {
    name: "Liechtenstein",
    dialCode: "+423",
    code: "LI",
    visited: false,
    posts: [],
  },
  {
    name: "Lithuania",
    dialCode: "+370",
    code: "LT",
    visited: false,
    posts: [],
  },
  {
    name: "Luxembourg",
    dialCode: "+352",
    code: "LU",
    visited: false,
    posts: [],
  },
  {
    name: "Macao",
    dialCode: "+853",
    code: "MO",
    visited: false,
    posts: [],
  },
  {
    name: "Macedonia",
    dialCode: "+389",
    code: "MK",
    visited: false,
    posts: [],
  },
  {
    name: "Madagascar",
    dialCode: "+261",
    code: "MG",
    visited: false,
    posts: [],
  },
  {
    name: "Malawi",
    dialCode: "+265",
    code: "MW",
    visited: false,
    posts: [],
  },
  {
    name: "Malaysia",
    dialCode: "+60",
    code: "MY",
    visited: true,
    year: 2022,
    posts: [],
  },
  {
    name: "Maldives",
    dialCode: "+960",
    code: "MV",
    visited: false,
    posts: [],
  },
  {
    name: "Mali",
    dialCode: "+223",
    code: "ML",
    visited: false,
    posts: [],
  },
  {
    name: "Malta",
    dialCode: "+356",
    code: "MT",
    visited: true,
    year: 2022,
    posts: [],
  },
  {
    name: "Marshall Islands",
    dialCode: "+692",
    code: "MH",
    visited: false,
    posts: [],
  },
  {
    name: "Martinique",
    dialCode: "+596",
    code: "MQ",
    visited: false,
    posts: [],
  },
  {
    name: "Mauritania",
    dialCode: "+222",
    code: "MR",
    visited: false,
    posts: [],
  },
  {
    name: "Mauritius",
    dialCode: "+230",
    code: "MU",
    visited: false,
    posts: [],
  },
  {
    name: "Mayotte",
    dialCode: "+262",
    code: "YT",
    visited: false,
    posts: [],
  },
  {
    name: "Mexico",
    dialCode: "+52",
    code: "MX",
    visited: true,
    year: 2022,
    posts: [],
  },
  {
    name: "Micronesia",
    dialCode: "+691",
    code: "FM",
    visited: false,
    posts: [],
  },
  {
    name: "Moldova",
    dialCode: "+373",
    code: "MD",
    visited: false,
    posts: [],
  },
  {
    name: "Monaco",
    dialCode: "+377",
    code: "MC",
    visited: false,
    posts: [],
  },
  {
    name: "Mongolia",
    dialCode: "+976",
    code: "MN",
    visited: false,
    posts: [],
  },
  {
    name: "Montenegro",
    dialCode: "+382",
    code: "ME",
    visited: true,
    year: 2022,
    posts: [],
  },
  {
    name: "Montserrat",
    dialCode: "+1664",
    code: "MS",
    visited: false,
    posts: [],
  },
  {
    name: "Morocco",
    dialCode: "+212",
    code: "MA",
    visited: false,
    posts: [],
  },
  {
    name: "Mozambique",
    dialCode: "+258",
    code: "MZ",
    visited: false,
    posts: [],
  },
  {
    name: "Myanmar",
    dialCode: "+95",
    code: "MM",
    visited: false,
    posts: [],
  },
  {
    name: "Namibia",
    dialCode: "+264",
    code: "NA",
    visited: true,
    year: 2019,
    posts: [],
  },
  {
    name: "Nauru",
    dialCode: "+674",
    code: "NR",
    visited: false,
    posts: [],
  },
  {
    name: "Nepal",
    dialCode: "+977",
    code: "NP",
    visited: false,
    posts: [],
  },
  {
    name: "Netherlands",
    dialCode: "+31",
    code: "NL",
    visited: false,
    posts: [],
  },
  {
    name: "Netherlands Antilles",
    dialCode: "+599",
    code: "AN",
    visited: false,
    posts: [],
  },
  {
    name: "New Caledonia",
    dialCode: "+687",
    code: "NC",
    visited: false,
    posts: [],
  },
  {
    name: "New Zealand",
    dialCode: "+64",
    code: "NZ",
    visited: true,
    year: 2017,
    posts: [],
  },
  {
    name: "Nicaragua",
    dialCode: "+505",
    code: "NI",
    visited: false,
    posts: [],
  },
  {
    name: "Niger",
    dialCode: "+227",
    code: "NE",
    visited: false,
    posts: [],
  },
  {
    name: "Nigeria",
    dialCode: "+234",
    code: "NG",
    visited: false,
    posts: [],
  },
  {
    name: "Niue",
    dialCode: "+683",
    code: "NU",
    visited: false,
    posts: [],
  },
  {
    name: "Norfolk Island",
    dialCode: "+672",
    code: "NF",
    visited: false,
    posts: [],
  },
  {
    name: "Northern Mariana Islands",
    dialCode: "+1670",
    code: "MP",
    visited: false,
    posts: [],
  },
  {
    name: "Norway",
    dialCode: "+47",
    code: "NO",
    visited: false,
    posts: [],
  },
  {
    name: "Oman",
    dialCode: "+968",
    code: "OM",
    visited: false,
    posts: [],
  },
  {
    name: "Pakistan",
    dialCode: "+92",
    code: "PK",
    visited: false,
    posts: [],
  },
  {
    name: "Palau",
    dialCode: "+680",
    code: "PW",
    visited: false,
    posts: [],
  },
  {
    name: "Palestinian Territory, Occupied",
    dialCode: "+970",
    code: "PS",
    visited: false,
    posts: [],
  },
  {
    name: "Panama",
    dialCode: "+507",
    code: "PA",
    visited: false,
    posts: [],
  },
  {
    name: "Papua New Guinea",
    dialCode: "+675",
    code: "PG",
    visited: false,
    posts: [],
  },
  {
    name: "Paraguay",
    dialCode: "+595",
    code: "PY",
    visited: false,
    posts: [],
  },
  {
    name: "Peru",
    dialCode: "+51",
    code: "PE",
    visited: false,
    posts: [],
  },
  {
    name: "Philippines",
    dialCode: "+63",
    code: "PH",
    visited: false,
    posts: [],
  },
  {
    name: "Pitcairn",
    dialCode: "+872",
    code: "PN",
    visited: false,
    posts: [],
  },
  {
    name: "Poland",
    dialCode: "+48",
    code: "PL",
    visited: false,
    posts: [],
  },
  {
    name: "Portugal",
    dialCode: "+351",
    code: "PT",
    visited: false,
    posts: [],
  },
  {
    name: "Puerto Rico",
    dialCode: "+1939",
    code: "PR",
    visited: false,
    posts: [],
  },
  {
    name: "Qatar",
    dialCode: "+974",
    code: "QA",
    visited: false,
    posts: [],
  },
  {
    name: "Romania",
    dialCode: "+40",
    code: "RO",
    visited: false,
    posts: [],
  },
  {
    name: "Russia",
    dialCode: "+7",
    code: "RU",
    visited: false,
    posts: [],
  },
  {
    name: "Rwanda",
    dialCode: "+250",
    code: "RW",
    visited: false,
    posts: [],
  },
  {
    name: "Reunion",
    dialCode: "+262",
    code: "RE",
    visited: false,
    posts: [],
  },
  {
    name: "Saint Barthelemy",
    dialCode: "+590",
    code: "BL",
    visited: false,
    posts: [],
  },
  {
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    dialCode: "+290",
    code: "SH",
    visited: false,
    posts: [],
  },
  {
    name: "Saint Kitts and Nevis",
    dialCode: "+1869",
    code: "KN",
    visited: false,
    posts: [],
  },
  {
    name: "Saint Lucia",
    dialCode: "+1758",
    code: "LC",
    visited: false,
    posts: [],
  },
  {
    name: "Saint Martin",
    dialCode: "+590",
    code: "MF",
    visited: false,
    posts: [],
  },
  {
    name: "Saint Pierre and Miquelon",
    dialCode: "+508",
    code: "PM",
    visited: false,
    posts: [],
  },
  {
    name: "Saint Vincent and the Grenadines",
    dialCode: "+1784",
    code: "VC",
    visited: false,
    posts: [],
  },
  {
    name: "Samoa",
    dialCode: "+685",
    code: "WS",
    visited: false,
    posts: [],
  },
  {
    name: "San Marino",
    dialCode: "+378",
    code: "SM",
    visited: false,
    posts: [],
  },
  {
    name: "Sao Tome and Principe",
    dialCode: "+239",
    code: "ST",
    visited: false,
    posts: [],
  },
  {
    name: "Saudi Arabia",
    dialCode: "+966",
    code: "SA",
    visited: false,
    posts: [],
  },
  {
    name: "Senegal",
    dialCode: "+221",
    code: "SN",
    visited: false,
    posts: [],
  },
  {
    name: "Serbia",
    dialCode: "+381",
    code: "RS",
    visited: false,
    posts: [],
  },
  {
    name: "Seychelles",
    dialCode: "+248",
    code: "SC",
    visited: false,
    posts: [],
  },
  {
    name: "Sierra Leone",
    dialCode: "+232",
    code: "SL",
    visited: false,
    posts: [],
  },
  {
    name: "Singapore",
    dialCode: "+65",
    code: "SG",
    visited: true,
    year: 2023,
    posts: [],
  },
  {
    name: "Slovakia",
    dialCode: "+421",
    code: "SK",
    visited: false,
    posts: [],
  },
  {
    name: "Slovenia",
    dialCode: "+386",
    code: "SI",
    visited: false,
    posts: [],
  },
  {
    name: "Solomon Islands",
    dialCode: "+677",
    code: "SB",
    visited: false,
    posts: [],
  },
  {
    name: "Somalia",
    dialCode: "+252",
    code: "SO",
    visited: false,
    posts: [],
  },
  {
    name: "South Africa",
    dialCode: "+27",
    code: "ZA",
    visited: false,
    posts: [],
  },
  {
    name: "South Sudan",
    dialCode: "+211",
    code: "SS",
    visited: false,
    posts: [],
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    dialCode: "+500",
    code: "GS",
    visited: false,
    posts: [],
  },
  {
    name: "Spain",
    dialCode: "+34",
    code: "ES",
    visited: false,
    posts: [],
  },
  {
    name: "Sri Lanka",
    dialCode: "+94",
    code: "LK",
    visited: false,
    posts: [],
  },
  {
    name: "Sudan",
    dialCode: "+249",
    code: "SD",
    visited: false,
    posts: [],
  },
  {
    name: "Suriname",
    dialCode: "+597",
    code: "SR",
    visited: false,
    posts: [],
  },
  {
    name: "Svalbard and Jan Mayen",
    dialCode: "+47",
    code: "SJ",
    visited: false,
    posts: [],
  },
  {
    name: "Swaziland",
    dialCode: "+268",
    code: "SZ",
    visited: false,
    posts: [],
  },
  {
    name: "Sweden",
    dialCode: "+46",
    code: "SE",
    visited: false,
    posts: [],
  },
  {
    name: "Switzerland",
    dialCode: "+41",
    code: "CH",
    visited: true,
    year: 2022,
    posts: ["post-1", "post-2", "post-3", "post-4", "post-5"],
  },
  {
    name: "Syria",
    dialCode: "+963",
    code: "SY",
    visited: false,
    posts: [],
  },
  {
    name: "Taiwan",
    dialCode: "+886",
    code: "TW",
    visited: true,
    year: 2018,
    posts: [],
  },
  {
    name: "Tajikistan",
    dialCode: "+992",
    code: "TJ",
    visited: false,
    posts: [],
  },
  {
    name: "Tanzania, United Republic of Tanzania",
    dialCode: "+255",
    code: "TZ",
    visited: false,
    posts: [],
  },
  {
    name: "Thailand",
    dialCode: "+66",
    code: "TH",
    visited: true,
    year: 2022,
    posts: [],
  },
  {
    name: "Timor-Leste",
    dialCode: "+670",
    code: "TL",
    visited: false,
    posts: [],
  },
  {
    name: "Togo",
    dialCode: "+228",
    code: "TG",
    visited: false,
    posts: [],
  },
  {
    name: "Tokelau",
    dialCode: "+690",
    code: "TK",
    visited: false,
    posts: [],
  },
  {
    name: "Tonga",
    dialCode: "+676",
    code: "TO",
    visited: false,
    posts: [],
  },
  {
    name: "Trinidad and Tobago",
    dialCode: "+1868",
    code: "TT",
    visited: false,
    posts: [],
  },
  {
    name: "Tunisia",
    dialCode: "+216",
    code: "TN",
    visited: false,
    posts: [],
  },
  {
    name: "Turkey",
    dialCode: "+90",
    code: "TR",
    visited: false,
    posts: [],
  },
  {
    name: "Turkmenistan",
    dialCode: "+993",
    code: "TM",
    visited: false,
    posts: [],
  },
  {
    name: "Turks and Caicos Islands",
    dialCode: "+1649",
    code: "TC",
    visited: false,
    posts: [],
  },
  {
    name: "Tuvalu",
    dialCode: "+688",
    code: "TV",
    visited: false,
    posts: [],
  },
  {
    name: "Uganda",
    dialCode: "+256",
    code: "UG",
    visited: false,
    posts: [],
  },
  {
    name: "Ukraine",
    dialCode: "+380",
    code: "UA",
    visited: false,
    posts: [],
  },
  {
    name: "United Arab Emirates",
    dialCode: "+971",
    code: "AE",
    visited: false,
    posts: [],
  },
  {
    name: "United Kingdom",
    dialCode: "+44",
    code: "GB",
    visited: false,
    posts: [],
  },
  {
    name: "United States of America",
    dialCode: "+1",
    code: "US",
    visited: true,
    year: 2022,
    posts: [],
  },
  {
    name: "Uruguay",
    dialCode: "+598",
    code: "UY",
    visited: false,
    posts: [],
  },
  {
    name: "Uzbekistan",
    dialCode: "+998",
    code: "UZ",
    visited: false,
    posts: [],
  },
  {
    name: "Vanuatu",
    dialCode: "+678",
    code: "VU",
    visited: false,
    posts: [],
  },
  {
    name: "Venezuela, Bolivarian Republic of Venezuela",
    dialCode: "+58",
    code: "VE",
    visited: false,
    posts: [],
  },
  {
    name: "Vietnam",
    dialCode: "+84",
    code: "VN",
    visited: true,
    year: 2022,
    posts: [],
  },
  {
    name: "Virgin Islands, British",
    dialCode: "+1284",
    code: "VG",
    visited: false,
    posts: [],
  },
  {
    name: "Virgin Islands, U.S.",
    dialCode: "+1340",
    code: "VI",
    visited: false,
    posts: [],
  },
  {
    name: "Wallis and Futuna",
    dialCode: "+681",
    code: "WF",
    visited: false,
    posts: [],
  },
  {
    name: "Yemen",
    dialCode: "+967",
    code: "YE",
    visited: false,
    posts: [],
  },
  {
    name: "Zambia",
    dialCode: "+260",
    code: "ZM",
    visited: false,
    posts: [],
  },
  {
    name: "Zimbabwe",
    dialCode: "+263",
    code: "ZW",
    visited: false,
    posts: [],
  },
];
